"""empty message

Revision ID: e0ae87188885
Revises: 903b97958b4a
Create Date: 2017-07-08 17:59:25.070043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0ae87188885'
down_revision = '903b97958b4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('about_me', sa.String(length=1000), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('meal_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_1', sa.Integer(), nullable=True),
    sa.Column('user_2', sa.Integer(), nullable=True),
    sa.Column('restaurant_name', sa.String(length=128), nullable=False),
    sa.Column('restaurant_address', sa.String(length=128), nullable=False),
    sa.Column('restaurant_picture', sa.BLOB(), nullable=True),
    sa.Column('meal_time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['user_1'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_2'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_1'),
    sa.UniqueConstraint('user_2')
    )
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_type', sa.String(length=64), nullable=False),
    sa.Column('location', sa.String(length=64), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('meal_time', sa.Time(), nullable=True),
    sa.Column('filled', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requests_created'), 'requests', ['created'], unique=False)
    op.create_index(op.f('ix_requests_updated'), 'requests', ['updated'], unique=False)
    op.create_table('proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_proposed_to', sa.Integer(), nullable=True),
    sa.Column('user_proposed_from', sa.Integer(), nullable=True),
    sa.Column('filled', sa.Boolean(), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.ForeignKeyConstraint(['user_proposed_from'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_proposed_to'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_proposed_from'),
    sa.UniqueConstraint('user_proposed_to')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proposals')
    op.drop_index(op.f('ix_requests_updated'), table_name='requests')
    op.drop_index(op.f('ix_requests_created'), table_name='requests')
    op.drop_table('requests')
    op.drop_table('meal_dates')
    op.drop_table('users')
    # ### end Alembic commands ###
